# SCS2013 Exercise 02 

**This exercise notebook will go through the variables, basic data types, and operators in Python:**

* Numbers (Numeric)
  * Integers (정수형)
  * Floating Points (실수형)
* Strings (문자열)
* Booleans (불)

## ``print()`` and Comments (``#``)

Before start, let's print 'Hello'. 

**``print()``** is used to display information to the user: It does not change values, variables, functions - just simply displays.

* Usage of ``print()``: if we want to print a text, it should be in quotes `` '' `` or `` ""``.

* We can print multiple values by separating them with commas `,`.

* ``#`` symbol is used to put **comments** in your code. The comments don't get executed.

In [ ]:
print('1: Hello!')
print('2: Python Programming', 10, 200)
print('3: My', 'Name', 'is', 'Alice')
print()
print('4: =====')

In [ ]:
a = 123
print(a)
# print('Hello!')

"""
This is a multi-line 
comments
print('Welcome!')
"""
print('Good!')

In [ ]:
# print your student id, major, and name!

## Variables (변수)

**Variable** is a space in the computer's memory where we can store data (number, text, ...). We use variable in Python to hold and manipulate values. Python does not require to declare a variable before use it. All we need is **assign** a variable a value. (**dynamically typed**)

All we need is to provide a variable **name** and assign it some **value**: using **'='** operator.
```
var_name = value
```

  * e.g.: ``my_num = 123``
  * A variable named ``my_num`` was created
  * The value ``123`` was assigned to the variable ``my_num``

In [ ]:
my_num = 123

In [ ]:
my_num

In [ ]:
my_num + my_num

In [ ]:
print(my_num)

In [ ]:
# can assign new value with different type of 'float'
my_num = 12.3

In [ ]:
my_num

In [ ]:
# can assign multiple values simultaneously
my_num1, my_num2 = 3, 5.6
print(my_num1, my_num2)

**Variable names**

Python allows you to name variables to your liking, as long as the names follow the rules:

* variable names may contain letters (알파벳 대소문자), digits (0-9) or the underscore character `_`
* variable names must begin with a letter from `A-Z` or `a-z` or the underscore `_`
* variable names may not be a keyword in Python: e.g., `and`
* Python's *keyword(예약어)* list includes:

  ``and, as, if, for, import, in, is, break, True, while, ... ``

In [ ]:
fish = 10
fish

In [ ]:
_uvar_ = 3
_uvar_

In [ ]:
a21 = 45
a21

In [ ]:
long_var_name_is_okay = 5
long_var_name_is_okay

In [ ]:
RemoteAddress = '1.2.3.4'
RemoteAddress

In [ ]:
`ticked = 1
`ticked

In [ ]:
21a = 'start with num'
21a

In [ ]:
and = 21
and

## Data Types (자료형)

Python supports numerical data types: 
* **integer (정수형)**: number without decimal point
* **floating point (실수형)**: number with decimal point

and also supports text data type:
* **string (문자열)**: text

and boolean data type:
* **bool (불)**: conditional statements `True` (참) / `False` (거짓)

Python tracks the **type** of the value assigned to a variable. 

* ``type()``: Check what the value type is

In [ ]:
x = 12
print(type(x))

In [ ]:
x = 12.0
print(type(x))

In [ ]:
x = 'Hello'
print(type(x))

In [ ]:
x = False
print(type(x))

The way of converting variables to different types is to use ``int()``, ``float()`` or ``str()``.

In [ ]:
x = 12
print(type(x))
print(x)

print(type(float(x)))
print(float(x))

print(type(str(x)))
print(str(x))

In [ ]:
x = 'hello'
print(type(x))
print(x)

print(type(float(x)))
print(float(x))

In [ ]:
x = '12'
print(type(x))
print(x)

print(type(float(x)))
print(float(x))

In [ ]:
a = 123
b = '20'
print(a + int(b))
print(a + float(b))

## Python Operators (연산자)

Let's play with Python Operators!

* **Assignment (할당)** operators: assigning values to variables 

* **Arithmetic (산술)** operators: mathematics operators 

* **Comparison (비교)** operators: constructing a conditional statement 

* **Logical (논리)** operators: combining conditional statements

* **Membership (구성원)** operators: checking if a group of values contains a sub-value 

* **Identity (식별)** operators: checking if two values are the same object with the same memory location

....

### Assignment Operators

Let's start with *assignment* operators:

* `=`: variable name goes on the left side & the value being assigned goes to the right side

In [ ]:
planet = 'Earth'
planet

### Arithmetic Operators 

Used for most basic mathematical operations 

* `+` Addition (더하기): adds values 
* `-` Subtraction (빼기): subtracts values
* `*` Multiplication (곱하기): multiplies values
* `/` Division (float) (나누기): divides the first value by the second value and returns value with decimals
* `//` Division (floor) (몫): divide two values and returns integers without decimals
* `%` Modulus (나머지): gives the remainder of a division result
* `**` Power (거듭제곱): raises the first value to the power of second value

In [ ]:
a = 5
b = 3

c = a + b
d = a - b
e = a * b
f = a / b
g = a // b
h = a % b
i = a ** b

print('a is', a, 'and b is', b)
print('a + b is', c)
print('a - b is', d)
print('a * b is', e)
print('a / b is', f)
print('a // b is', g)
print('a % b is', h)
print('a ** b is', i)

In [ ]:
# division operator returns value with decimals (항상 계산 결과를 소수점이 있는 실수 형태로 반환)
print(10/1)
print(10/2)
print(10/3)
print(10/4)
print(10/5)

### Comparison Operators 

* returns "**boolean** values (True or False)" of the comparison results
* `==` Equal: returns True if left side is equal to the right side
* `!=` Not equal: returns True if left side is not equal to right side
* `>` Greater than: returns True if left side is grater than the right side
* `<` Less than: returns True if left side is less than the right side
* `>=` Greater than or equal to: returns True if left side is grater than or equal to the right side
* `<=` Less than: returns True if left side is less than or equal to the right side

In [ ]:
a = 5
b = 3

c = a == b
d = a != b
e = a > b
f = a < b
g = a >= b
h = a <= b

print('a is', a, 'and b is', b)
print('a == b is', c)
print('a != b is', d)
print('a > b is', e)
print('a < b is', f)
print('a >= b is', g)
print('a <= b is', h)

### Logical Operators 
* returns "**boolean** values (True or False)" 
* `and` logical AND: returns True when both operatnds are True (논리곱: 두개의 명제가 모두 참인지 판단)
* `or` logical OR: returns True if at least one of the operands is True (논리합: 적어도 한개 이상의 참이 있는지 판단)
* `not` logical NOT: returns True if operand is False

In [ ]:
x = 5
print(x > 3 and x < 10)

In [ ]:
x = 15
print(x > 3 and x < 10)

In [ ]:
x = 5
print(x > 3 or x < 4)

In [ ]:
x = 5
print(x < 2 or x > 6)

### Membership Operators / Identity Operators 

* returns "**boolean** values (True or False)" 
* `in`: return True if an object is in another object
* `not in`: return True if an object is not in another object

* `is`: tells if two objects are identical
* `is not`: tells if two objects are not identical

**Note** that `is` returns False if it is not the same object, even if they have the same content

In [ ]:
x = ['apple', 'banana']
print('apple' in x)
print('pear' in x)

In [ ]:
a = 10
b = 3
A = {1,2,3,4,5}
print(a in A)
print(b in A)

In [ ]:
a, b = 5, 5
print(id(a), id(b))
print(a is b)
print(a == b)

In [ ]:
a, b = 56, 92
print(id(a), id(b))
print(a is b)
print(a == b)

In [ ]:
x = 1000
print(x, id(x))
y = 1001
print(y, id(y))
y = y-1
print(y, id(y))

print(x is y)
print(x == y)

### More Assignment Operators 

* `+=`: adding values and assigning it: `a+=b` instead of `a=a+b`
* Similarly, we can use `-=`, `*=`, `/=`, `%=`, `//=`, `**=`, ...

In [ ]:
x = 5
print('x is', x)

x += 3
print('x += 3 is', x)

x -= 2
print('x += 2 is', x)

x *= 1.5
print('x *= 1.5 is', x)

x /= 1.25
print('x /= 1.25 is', x)

x //= 3
print('x //= 3 is', x)

x **= 4
print('x **= 4 is', x)

## Exercises 

Let's check out some exercises that will help you understand **print, variables, data types and operators in Python** better.

### E-1

Try to print a sentence "Hello Everyone! Good to see you!!" directly - using `print()` function.

In [ ]:
# your code here: print a sentence directly

### E-2

Assign `13` to variable `num_of_boxes`, and see what sentence is printed.

In [ ]:
# your code here: assign a number 13 to the variable num_of_boxes


print('There are', num_of_boxes, 'boxes on the table.')

### E-3

Now assign a new value `5.3` to the variable `num_of_boxes` and print the value.

In [ ]:
# your code here: assign a new value 5.3 to the variable and print the value


print('Now there are', num_of_boxes, 'boxes on the table?!')

### E-4

Now check out **string** data type. Assign any string (a short sentence or a couple of words) to the variable `my_str` and print it. 

* You need to use the quote to make the string data.

In [ ]:
# your code here: assign any short sentence or a couple of words to the variable `my_str and print it

### E-5

Create three variables and assign following three scores, and compute their average value.
```
Python: 85
Java: 77
R: 52
```

In [ ]:
# your code here: make three variables



# your code here: average scores, and print it

### E-6

Use the correct membership operator to check 1) if `'apple'` is present in the `fruits` variable, 2) if `'milk'` is present in the `fruits`.

In [ ]:
fruits = ['apple', 'banana', 'melon']

# your code here: check if 'apple' is present in the `fruits` variable


# your code here: check if 'milk' is present in the `fruits` variable

### E-7

Check if `num` is a four digit (네자리수) odd (홀수) number.
* 네자리수를 판단하기 위한 여러가지 방법을 고민해보기

In [ ]:
num = 25

# your code here: check_1: check if num is a four digit number
check_1 = 

# your code here: check_2: check if num is an odd number
check_2 = 

# check: check if num is a four-digit odd number
check = 

print('num', num, 'is a four digit number:', check_1)
print('num', num, 'is an odd number:', check_2)
print('num', num, 'is a four digit odd number:', check)